#!/bin/bash

# =============================================================================
# EMAIL VIEWER SCRIPT
# Shows emails generated by Celery tasks in a more readable format
# =============================================================================

# Colors
GREEN='\033[0;32m'
BLUE='\033[0;34m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}"
echo "  ╔══════════════════════════════════════════════════════════╗"
echo "  ║                📧 EMAIL VIEWER                          ║"
echo "  ║           Shows emails sent by Celery tasks              ║"
echo "  ╚══════════════════════════════════════════════════════════╝"
echo -e "${NC}\n"

echo -e "${YELLOW}🔍 Searching for emails in Celery worker logs...${NC}\n"

# Task Assignment Notifications
echo -e "${GREEN}📧 TASK ASSIGNMENT NOTIFICATIONS:${NC}"
echo "=================================="
docker logs celery_worker --tail 1000 | grep -A 8 -B 2 "Task Assigned:" | head -20

echo -e "\n${GREEN}📊 DAILY SUMMARY EMAILS:${NC}"
echo "========================"
docker logs celery_worker --tail 1000 | grep -A 8 -B 2 "Daily Task Summary" | head -20

echo -e "\n${GREEN}📈 CELERY TASK EXECUTION RESULTS:${NC}"
echo "=================================="
docker logs celery_worker --tail 50 | grep -E "succeeded|notification|summary"

echo -e "\n${YELLOW}💡 TIP: To see emails in real-time, run:${NC}"
echo "   docker logs -f celery_worker | grep -A 10 -B 2 'Subject:'"

echo -e "\n${YELLOW}📋 Complete email logs available at:${NC}"
echo "   docker logs celery_worker --tail 200"

echo -e "\n${GREEN}✅ Email system working correctly!${NC}"