# Generated by Django 5.2.6 on 2025-09-07 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_remove_customuser_email_hash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='last_2fa_code',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='last_2fa_time',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='two_factor_enabled',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='two_factor_secret',
        ),
    ]
