# Generated by Django 5.2.6 on 2025-09-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_optimize_database_performance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('todo', 'To Do'), ('pending', 'Pending'), ('in_progress', 'In Progress'), ('review', 'In Review'), ('done', 'Done'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='todo', max_length=20),
        ),
    ]
