# Generated by Django 5.2.6 on 2025-09-27 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_description_alter_task_metadata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='template',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='task',
        ),
        migrations.RemoveField(
            model_name='timelog',
            name='user',
        ),
        migrations.DeleteModel(
            name='TaskTemplate',
        ),
        migrations.DeleteModel(
            name='TimeLog',
        ),
    ]
